brewtopia/brewtopia/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('shop/', include('shop.urls')),
    path('order/', include('orders.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

brewtopia/shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.shop, name='shop'),
    path('category/<slug:category_slug>/', views.shop, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_info, name='product_info'),
    path('search/', views.search, name='search'),
] 

brewtopia/users/urls.py
from django.urls import path
from . import views
from .Errors.handlers import handle_not_found, handle_server_error

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

brewtopia/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
# Create your models here.

class MyAccountManager(BaseUserManager):

    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError('User must have an email addres')
        if not username:
            raise ValueError('User must have an username')
        
        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
        )

        user.set_password(password)
        user.save(using = self._db)
        return user
        
    def create_superuser(self, first_name, last_name, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password,
            first_name=first_name,
            last_name=last_name,
        )
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin =True
        user.save(using = self._db)
        return user


class UserProfile(AbstractBaseUser):
    first_name      = models.CharField(max_length=50)
    last_name       = models.CharField(max_length=50)
    username        = models.CharField(max_length=50, unique=True)
    email           = models.EmailField(max_length=50,unique=True)
    phone_number    = models.CharField(max_length=50)

    #required
    date_joined     = models.DateTimeField(auto_now_add=True)
    last_login      = models.DateTimeField(auto_now_add=True)
    is_admin        = models.BooleanField(default=False)
    is_staff        = models.BooleanField(default=False)
    is_active       = models.BooleanField(default=False)
    is_superadmin   = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = MyAccountManager()

    def __str__(self):
        return self.email
    
    def has_perm(self, perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self, add_label):
        return True

brewtopia/users/forms.py
from django import forms
from .models import UserProfile


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Password',
        'class': 'form-control',
    }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password'
    }))
    
    class Meta:
        model = UserProfile
        fields = ['first_name', 'last_name', 'phone_number', 'email', 'password']
    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError(
                "Password does not match!"
            )

            
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter First Name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter last Name'
        self.fields['phone_number'].widget.attrs['placeholder'] = 'Enter Phone Number'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter Email Address'
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

brewtopia/users/views.py
from django.shortcuts import render, redirect
from .forms import RegistrationForm
from .models import UserProfile
from django.contrib.auth.decorators import login_required
from django.contrib import messages, auth
from orders.models import Order, OrderItem
from orders.views import _order_id

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            phone_number = form.cleaned_data['phone_number']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            username = email.split("@")[0]
            user = UserProfile.objects.create_user(first_name=first_name, last_name=last_name, email=email, username=username, password=password)
            user.phone_number = phone_number
            user.save()
            messages.success(request,'Registration succesful')
            return redirect('users:register')
    else:
        form = RegistrationForm()
    
    context = {
        'form':form,
    }
    return render(request, 'user_accounts/register.html', context)
def login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        
        user = auth.authenticate(email=email, password=password)

        if user is not None:
            try:
                order = Order.objects.get(order_id=_order_id(request))
                is_order_item_exists = OrderItem.objects.filter(order=order).exists()
                if is_order_item_exists:
                    order_item = OrderItem.objects.filter(order=order)
                    
                    for item in order_item:
                        item.user = user
                        item.save()

            except:
                pass
            auth.login(request, user)
            # messages.success(request, 'You are now logged in.')
            return redirect('users:dashboard')
        else:
            messages.error(request, "Invalid login credentials")
            return redirect('login')
    return render(request, 'user_accounts/login.html')

@login_required(login_url = 'login')
def logout(request):
    auth.logout(request)
    messages.success(request,'You are logged out')
    return redirect('users:login')

@login_required(login_url = 'login')
def dashboard(request):
    return render(request, 'users/home.html')

brewtopia/users/templates/users/inside/footer.html
<footer class="section-footer border-top">
	<div class="container">
		<section class="footer-bottom border-top row">
			<div class="col-md-2">
				<p class="text-muted"> &copy 2023 BREWTOPIA </p>
			</div>
			<div class="col-md-8 text-md-center">
				<span  class="px-2">brewtopia@gmail.com</span>
				<span  class="px-2">+777-734-20-42</span>
				<span  class="px-2">Astana</span>
			</div>
			<div class="col-md-2 text-md-right text-muted">
				<i class="fab fa-lg fa-cc-visa"></i>
				<i class="fab fa-lg fa-cc-paypal"></i>
				<i class="fab fa-lg fa-cc-mastercard"></i>
			</div>
		</section>
	</div><!-- //container -->
</footer>

brewtopia/users/templates/users/inside/header.html
{% load static %}
<header class="section-header">
 
    <section class="header-main border-bottom">
        <div class="container">
    <div class="row align-items-center">
        <div class="col-lg-3 col-md-3 col-6">
            <a href="{% url 'home' %}" class="logo">
                <img class="logo" src="{% static 'users/images/logogo.jpg' %}">
            </a> <!-- brand-wrap.// -->
        </div>
        <div class="col-lg col-sm col-md col-6 flex-grow-0">
            <div class="category-wrap dropdown d-inline-block float-right">
                <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown"> 
                    <i class="fa fa-bars"></i> Меню
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'shop' %}">Все </a>
                        {% for category in links %}
                        <a class="dropdown-item" href="{{ category.get_url }}">{{ category.category_name }} </a>
                        {% endfor %}
                </div>
            </div>  <!-- category-wrap.// -->
        </div> <!-- col.// -->
        <a href="{% url 'shop' %}" class="btn btn-outline-info">Магазин</a>
        <div class="col-lg  col-md-6 col-sm-12 col">
            <form action="{% url 'search' %}" class="search" method="GET">
                <div class="input-group w-100">
                    <input type="text" class="form-control" style="width:60%;" placeholder="Search" name="keyword">
                    
                    <div class="input-group-append">
                      <button class="btn btn-default" type="submit">
                        <i class="fa fa-search"></i>
                      </button>
                    </div>
                </div>
            </form> <!-- search-wrap .end// -->
        </div> <!-- col.// -->
        <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
                    <div class="d-flex justify-content-end mb-3 mb-lg-0">
                        {% if user.id is not None %}
                        <div class="widget-header">
                            <small class="title text-muted">Добро пожаловать {{ user.first_name }}!</small>
                            <div> 
                                <a href="#"></a> <span class="dark-transp"> | </span>
                                <a href="{% url 'users:logout' %}"> Выйти </a>
                            </div>
                        </div>
                        {% else %}
                        <div class="widget-header">
                            <small class="title text-muted">Добро пожаловать гость!</small>
                            <div> 
                                <a href="{% url 'users:login' %}">Войти</a> <span class="dark-transp"> | </span>
                                <a href="{% url 'users:register' %}"> Регистрация </a>
                            </div>
                        </div>
                        {% endif %}
                        <a href="{% url 'order' %}" class="widget-header pl-3 ml-3">
                            <div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
                            <span class="badge badge-pill badge-danger notify">{{ order_count }}</span>
                        </a>
                    </div> <!-- widgets-wrap.// -->
                </div> <!-- col.// -->
    </div> <!-- row.// -->
        </div> <!-- container.// -->
    </section> <!-- header-main .// -->
    
    
    
    
    </header> <!-- section-header.// -->